const host={
	sat:'http://www.baidu.com.sat',
	uat:'http://www.baidu.com.uat',
	dev:'http://www.baidu.com.dev'
};
module.exports={
	port:8823,
	proxy:{
		'(/basic/**)|(/permission/**)|(/trade/**)':{
			target:host.uat,
			changeOrigin:true,
			pathRewrite:{
				'^/basic':''
			}
		},
	},
	overLay:false,
	autoOpenBrowser:false
}